/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ZapSideDrawer {
    'open': boolean;
    'openDrawer': () => Promise<void>;
    'title': string;
  }
  interface ZapStockPrice {}
  interface ZapTooltip {
    'displayTooltip': boolean;
    'tooltipText': string;
  }
}

declare global {


  interface HTMLZapSideDrawerElement extends Components.ZapSideDrawer, HTMLStencilElement {}
  var HTMLZapSideDrawerElement: {
    prototype: HTMLZapSideDrawerElement;
    new (): HTMLZapSideDrawerElement;
  };

  interface HTMLZapStockPriceElement extends Components.ZapStockPrice, HTMLStencilElement {}
  var HTMLZapStockPriceElement: {
    prototype: HTMLZapStockPriceElement;
    new (): HTMLZapStockPriceElement;
  };

  interface HTMLZapTooltipElement extends Components.ZapTooltip, HTMLStencilElement {}
  var HTMLZapTooltipElement: {
    prototype: HTMLZapTooltipElement;
    new (): HTMLZapTooltipElement;
  };
  interface HTMLElementTagNameMap {
    'zap-side-drawer': HTMLZapSideDrawerElement;
    'zap-stock-price': HTMLZapStockPriceElement;
    'zap-tooltip': HTMLZapTooltipElement;
  }
}

declare namespace LocalJSX {
  interface ZapSideDrawer {
    'open'?: boolean;
    'title'?: string;
  }
  interface ZapStockPrice {}
  interface ZapTooltip {
    'displayTooltip'?: boolean;
    'tooltipText'?: string;
  }

  interface IntrinsicElements {
    'zap-side-drawer': ZapSideDrawer;
    'zap-stock-price': ZapStockPrice;
    'zap-tooltip': ZapTooltip;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'zap-side-drawer': LocalJSX.ZapSideDrawer & JSXBase.HTMLAttributes<HTMLZapSideDrawerElement>;
      'zap-stock-price': LocalJSX.ZapStockPrice & JSXBase.HTMLAttributes<HTMLZapStockPriceElement>;
      'zap-tooltip': LocalJSX.ZapTooltip & JSXBase.HTMLAttributes<HTMLZapTooltipElement>;
    }
  }
}


